version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - data01:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    ports:
      - 5601:5601
  mqtt:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
  wamp-mqtt:
    image: docker.smartplatform.io/wamp-mqtt-bridge:2.1
    depends_on:
      - mqtt
    volumes:
      - './config.ini:/opt/app/config.ini'
volumes:
  data01:
    driver: local
