version: '3.8'

services:
  mqtt-to-kafka:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MQTT_BROKER: "broker"
      MQTT_PORT: 1883
      MQTT_TOPIC: "#"
      KAFKA_BROKER: "broker:29092"
      KAFKA_TOPIC: "mqtt"
    extra_hosts:
      - "broker:192.168.205.8"
